apiVersion: v1
kind: PersistentVolume
metadata:
  name: counter
  labels:
    type: local
spec:
  storageClassName: efs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/app/"
    
